import "./globals.css";
import "mvp.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>Список дел</h1>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
